services:
  backend:
    build: ./backend
    container_name: smartflow-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app
    restart: always

  frontend:
    build: ./frontend
    container_name: smartflow-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/vite.config.ts:/app/vite.config.ts
    depends_on:
      - backend
    restart: always
